name: 'Await Taktile Deployment'
author: Taktile
description: 'Wait until your new deployment is live on Taktile'
inputs:
  TKTL_API_KEY:
    description: 'Your Taktile API key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.TKTL_API_KEY }}
branding:
  icon: 'rotate-ccw'
  color: 'green'